{
   "numberOfSchools": 2913,
      "numberOfPages": 292,
         "schoolList": [
            {
               "schoolid": "530486002475",
               "schoolName": "10th Street School",
               "phone": "(360) 965-0400",
               "url": "https://www.schooldigger.com/go/WA/schools/0486002475/school.aspx",
               "urlCompare": "https://www.schooldigger.com/go/WA/schools/0486002475/search.aspx",
               "address": {
                  "latLong": {
                     "latitude": 48.057438,
                     "longitude": -122.18199
                  },
                  "street": "7204 27th Ave NE",
                  "city": "Marysville",
                  "state": "WA",
                  "stateFull": "Washington",
                  "zip": "98271",
                  "zip4": "",
                  "cityURL": "https://www.schooldigger.com/go/WA/city/Marysville/search.aspx",
                  "zipURL": "https://www.schooldigger.com/go/WA/zip/98271/search.aspx",
                  "html": "7204 27th Ave NE<br />Marysville, WA 98271"
               },
               "lowGrade": "6",
               "highGrade": "8",
               "schoolLevel": "Middle",
               "isCharterSchool": "No",
               "isMagnetSchool": "(n/a)",
               "isVirtualSchool": "No",
               "isTitleISchool": "No",
               "isTitleISchoolwideSchool": "No",
               "district": {
                  "districtID": "5304860",
                  "districtName": "Marysville School District",
                  "url": "https://www.schooldigger.com/go/WA/district/04860/search.aspx",
                  "rankURL": "https://www.schooldigger.com/go/WA/districtrank.aspx?finddistrict=04860"
               },
               "county": {
                  "countyName": "Snohomish",
                  "countyURL": "https://www.schooldigger.com/go/WA/county/Snohomish/search.aspx"
               },
               "rankHistory": [
                  {
                     "year": 2018,
                     "rank": 165,
                     "rankOf": 437,
                     "rankStars": 3,
                     "rankLevel": "Middle",
                     "rankStatewidePercentage": 62.24,
                     "averageStandardScore": 59.25267
                  },
                  {
                     "year": 2017,
                     "rank": 119,
                     "rankOf": 435,
                     "rankStars": 4,
                     "rankLevel": "Middle",
                     "rankStatewidePercentage": 72.64,
                     "averageStandardScore": 69.86031
                  }
               ],
               "rankMovement": -46,
               "locationIsWithinBoundary": null,
               "schoolYearlyDetails": [
                  {
                     "year": 2017,
                     "numberOfStudents": 181,
                     "percentFreeDiscLunch": 17.13,
                     "percentofAfricanAmericanStudents": 1.1,
                     "percentofAsianStudents": 3.31,
                     "percentofHispanicStudents": 11.05,
                     "percentofIndianStudents": 3.87,
                     "percentofPacificIslanderStudents": null,
                     "percentofWhiteStudents": 71.27,
                     "percentofTwoOrMoreRaceStudents": 9.39,
                     "percentofUnspecifiedRaceStudents": null,
                     "teachersFulltime": 7.3,
                     "pupilTeacherRatio": 24.7,
                     "numberofAfricanAmericanStudents": 2,
                     "numberofAsianStudents": 6,
                     "numberofHispanicStudents": 20,
                     "numberofIndianStudents": 7,
                     "numberofPacificIslanderStudents": null,
                     "numberofWhiteStudents": 129,
                     "numberofTwoOrMoreRaceStudents": 17,
                     "numberofUnspecifiedRaceStudents": null
                  },
                  {
                     "year": 2016,
                     "numberOfStudents": 171,
                     "percentFreeDiscLunch": 18.13,
                     "percentofAfricanAmericanStudents": 0.58,
                     "percentofAsianStudents": 2.92,
                     "percentofHispanicStudents": 11.7,
                     "percentofIndianStudents": 4.68,
                     "percentofPacificIslanderStudents": 0,
                     "percentofWhiteStudents": 71.35,
                     "percentofTwoOrMoreRaceStudents": 8.77,
                     "percentofUnspecifiedRaceStudents": null,
                     "teachersFulltime": 7,
                     "pupilTeacherRatio": 24.4,
                     "numberofAfricanAmericanStudents": 1,
                     "numberofAsianStudents": 5,
                     "numberofHispanicStudents": 20,
                     "numberofIndianStudents": 8,
                     "numberofPacificIslanderStudents": 0,
                     "numberofWhiteStudents": 122,
                     "numberofTwoOrMoreRaceStudents": 15,
                     "numberofUnspecifiedRaceStudents": null
                  }
               ],
               "isPrivate": false,
               "privateDays": null,
               "privateHours": null,
               "privateHasLibrary": null,
               "privateCoed": null,
               "privateOrientation": null,
               "hasBoundary": true
            },
            {
               "schoolid": "530270001270",
               "schoolName": "49th Street Academy",
               "phone": "(360) 604-6700",
               "url": "https://www.schooldigger.com/go/WA/schools/0270001270/school.aspx",
               "urlCompare": "https://www.schooldigger.com/go/WA/schools/0270001270/search.aspx",
               "address": {
                  "latLong": {
                     "latitude": 45.656452,
                     "longitude": -122.522635
                  },
                  "street": "14619B NE 49th Street",
                  "city": "Vancouver",
                  "state": "WA",
                  "stateFull": "Washington",
                  "zip": "98682",
                  "zip4": "6308",
                  "cityURL": "https://www.schooldigger.com/go/WA/city/Vancouver/search.aspx",
                  "zipURL": "https://www.schooldigger.com/go/WA/zip/98682/search.aspx",
                  "html": "14619B NE 49th Street<br />Vancouver, WA 98682-6308"
               },
               "lowGrade": "K",
               "highGrade": "12",
               "schoolLevel": "Alternative",
               "isCharterSchool": "No",
               "isMagnetSchool": "(n/a)",
               "isVirtualSchool": "No",
               "isTitleISchool": "No",
               "isTitleISchoolwideSchool": "No",
               "district": {
                  "districtID": "5302700",
                  "districtName": "Evergreen School District (Clark)",
                  "url": "https://www.schooldigger.com/go/WA/district/02700/search.aspx",
                  "rankURL": "https://www.schooldigger.com/go/WA/districtrank.aspx?finddistrict=02700"
               },
               "county": {
                  "countyName": "Clark",
                  "countyURL": "https://www.schooldigger.com/go/WA/county/Clark/search.aspx"
               },
               "rankHistory": null,
               "rankMovement": null,
               "locationIsWithinBoundary": null,
               "schoolYearlyDetails": [
                  {
                     "year": 2017,
                     "numberOfStudents": 107,
                     "percentFreeDiscLunch": 69.16,
                     "percentofAfricanAmericanStudents": 10.28,
                     "percentofAsianStudents": 8.41,
                     "percentofHispanicStudents": 13.08,
                     "percentofIndianStudents": 0.93,
                     "percentofPacificIslanderStudents": 0,
                     "percentofWhiteStudents": 63.55,
                     "percentofTwoOrMoreRaceStudents": 3.74,
                     "percentofUnspecifiedRaceStudents": null,
                     "teachersFulltime": 13,
                     "pupilTeacherRatio": 8.1,
                     "numberofAfricanAmericanStudents": 11,
                     "numberofAsianStudents": 9,
                     "numberofHispanicStudents": 14,
                     "numberofIndianStudents": 1,
                     "numberofPacificIslanderStudents": 0,
                     "numberofWhiteStudents": 68,
                     "numberofTwoOrMoreRaceStudents": 4,
                     "numberofUnspecifiedRaceStudents": null
                  },
                  {
                     "year": 2016,
                     "numberOfStudents": 99,
                     "percentFreeDiscLunch": 62.63,
                     "percentofAfricanAmericanStudents": 9.09,
                     "percentofAsianStudents": 3.03,
                     "percentofHispanicStudents": 10.1,
                     "percentofIndianStudents": 1.01,
                     "percentofPacificIslanderStudents": 2.02,
                     "percentofWhiteStudents": 69.7,
                     "percentofTwoOrMoreRaceStudents": 5.05,
                     "percentofUnspecifiedRaceStudents": null,
                     "teachersFulltime": 12,
                     "pupilTeacherRatio": 8.2,
                     "numberofAfricanAmericanStudents": 9,
                     "numberofAsianStudents": 3,
                     "numberofHispanicStudents": 10,
                     "numberofIndianStudents": 1,
                     "numberofPacificIslanderStudents": 2,
                     "numberofWhiteStudents": 69,
                     "numberofTwoOrMoreRaceStudents": 5,
                     "numberofUnspecifiedRaceStudents": null
                  }
               ],
               "isPrivate": false,
               "privateDays": null,
               "privateHours": null,
               "privateHasLibrary": null,
               "privateCoed": null,
               "privateOrientation": null,
               "hasBoundary": false
            },
            {
               "schoolid": "530910002602",
               "schoolName": "A G West Black Hills High School",
               "phone": "(360) 709-7800",
               "url": "https://www.schooldigger.com/go/WA/schools/0910002602/school.aspx",
               "urlCompare": "https://www.schooldigger.com/go/WA/schools/0910002602/search.aspx",
               "address": {
                  "latLong": {
                     "latitude": 46.978091,
                     "longitude": -122.948107
                  },
                  "street": "7741 Littlerock Road SW",
                  "city": "Tumwater",
                  "state": "WA",
                  "stateFull": "Washington",
                  "zip": "98512",
                  "zip4": "",
                  "cityURL": "https://www.schooldigger.com/go/WA/city/Tumwater/search.aspx",
                  "zipURL": "https://www.schooldigger.com/go/WA/zip/98512/search.aspx",
                  "html": "7741 Littlerock Road SW<br />Tumwater, WA 98512"
               },
               "lowGrade": "9",
               "highGrade": "12",
               "schoolLevel": "High",
               "isCharterSchool": "No",
               "isMagnetSchool": "(n/a)",
               "isVirtualSchool": "No",
               "isTitleISchool": "No",
               "isTitleISchoolwideSchool": "No",
               "district": {
                  "districtID": "5309100",
                  "districtName": "Tumwater School District",
                  "url": "https://www.schooldigger.com/go/WA/district/09100/search.aspx",
                  "rankURL": "https://www.schooldigger.com/go/WA/districtrank.aspx?finddistrict=09100"
               },
               "county": {
                  "countyName": "Thurston",
                  "countyURL": "https://www.schooldigger.com/go/WA/county/Thurston/search.aspx"
               },
               "rankHistory": null,
               "rankMovement": null,
               "locationIsWithinBoundary": null,
               "schoolYearlyDetails": [
                  {
                     "year": 2017,
                     "numberOfStudents": 873,
                     "percentFreeDiscLunch": 25.89,
                     "percentofAfricanAmericanStudents": 2.41,
                     "percentofAsianStudents": 4.01,
                     "percentofHispanicStudents": 8.48,
                     "percentofIndianStudents": 0.69,
                     "percentofPacificIslanderStudents": 0.57,
                     "percentofWhiteStudents": 75.37,
                     "percentofTwoOrMoreRaceStudents": 8.48,
                     "percentofUnspecifiedRaceStudents": null,
                     "teachersFulltime": 41.8,
                     "pupilTeacherRatio": 20.8,
                     "numberofAfricanAmericanStudents": 21,
                     "numberofAsianStudents": 35,
                     "numberofHispanicStudents": 74,
                     "numberofIndianStudents": 6,
                     "numberofPacificIslanderStudents": 5,
                     "numberofWhiteStudents": 658,
                     "numberofTwoOrMoreRaceStudents": 74,
                     "numberofUnspecifiedRaceStudents": null
                  },
                  {
                     "year": 2016,
                     "numberOfStudents": 873,
                     "percentFreeDiscLunch": 23.94,
                     "percentofAfricanAmericanStudents": 2.29,
                     "percentofAsianStudents": 4.47,
                     "percentofHispanicStudents": 7.9,
                     "percentofIndianStudents": 0.69,
                     "percentofPacificIslanderStudents": 0.57,
                     "percentofWhiteStudents": 75.72,
                     "percentofTwoOrMoreRaceStudents": 8.36,
                     "percentofUnspecifiedRaceStudents": null,
                     "teachersFulltime": 41,
                     "pupilTeacherRatio": 21.2,
                     "numberofAfricanAmericanStudents": 20,
                     "numberofAsianStudents": 39,
                     "numberofHispanicStudents": 69,
                     "numberofIndianStudents": 6,
                     "numberofPacificIslanderStudents": 5,
                     "numberofWhiteStudents": 661,
                     "numberofTwoOrMoreRaceStudents": 73,
                     "numberofUnspecifiedRaceStudents": null
                  }
               ],
               "isPrivate": false,
               "privateDays": null,
               "privateHours": null,
               "privateHasLibrary": null,
               "privateCoed": null,
               "privateOrientation": null,
               "hasBoundary": true
            },
            {
               "schoolid": "530003000001",
               "schoolName": "A J West Elementary",
               "phone": "(360) 538-2131",
               "url": "https://www.schooldigger.com/go/WA/schools/0003000001/school.aspx",
               "urlCompare": "https://www.schooldigger.com/go/WA/schools/0003000001/search.aspx",
               "address": {
                  "latLong": {
                     "latitude": 46.972045,
                     "longitude": -123.837911
                  },
                  "street": "1801 Bay Ave.",
                  "city": "Aberdeen",
                  "state": "WA",
                  "stateFull": "Washington",
                  "zip": "98520",
                  "zip4": "5510",
                  "cityURL": "https://www.schooldigger.com/go/WA/city/Aberdeen/search.aspx",
                  "zipURL": "https://www.schooldigger.com/go/WA/zip/98520/search.aspx",
                  "html": "1801 Bay Ave.<br />Aberdeen, WA 98520-5510"
               },
               "lowGrade": "PK",
               "highGrade": "6",
               "schoolLevel": "Elementary",
               "isCharterSchool": "No",
               "isMagnetSchool": "(n/a)",
               "isVirtualSchool": "No",
               "isTitleISchool": "Yes",
               "isTitleISchoolwideSchool": "No",
               "district": {
                  "districtID": "5300030",
                  "districtName": "Aberdeen School District",
                  "url": "https://www.schooldigger.com/go/WA/district/00030/search.aspx",
                  "rankURL": "https://www.schooldigger.com/go/WA/districtrank.aspx?finddistrict=00030"
               },
               "county": {
                  "countyName": "Grays Harbor",
                  "countyURL": "https://www.schooldigger.com/go/WA/county/Grays+Harbor/search.aspx"
               },
               "rankHistory": [
                  {
                     "year": 2018,
                     "rank": 966,
                     "rankOf": 1054,
                     "rankStars": 0,
                     "rankLevel": "Elementary",
                     "rankStatewidePercentage": 8.35,
                     "averageStandardScore": 12.87274
                  },
                  {
                     "year": 2017,
                     "rank": 970,
                     "rankOf": 1056,
                     "rankStars": 0,
                     "rankLevel": "Elementary",
                     "rankStatewidePercentage": 8.14,
                     "averageStandardScore": 12.37056
                  }
               ],
               "rankMovement": 4,
               "locationIsWithinBoundary": null,
               "schoolYearlyDetails": [
                  {
                     "year": 2017,
                     "numberOfStudents": 407,
                     "percentFreeDiscLunch": 76.17,
                     "percentofAfricanAmericanStudents": 0.74,
                     "percentofAsianStudents": 0.98,
                     "percentofHispanicStudents": 41.03,
                     "percentofIndianStudents": 2.7,
                     "percentofPacificIslanderStudents": null,
                     "percentofWhiteStudents": 47.42,
                     "percentofTwoOrMoreRaceStudents": 7.13,
                     "percentofUnspecifiedRaceStudents": null,
                     "teachersFulltime": 27.7,
                     "pupilTeacherRatio": 14.6,
                     "numberofAfricanAmericanStudents": 3,
                     "numberofAsianStudents": 4,
                     "numberofHispanicStudents": 167,
                     "numberofIndianStudents": 11,
                     "numberofPacificIslanderStudents": null,
                     "numberofWhiteStudents": 193,
                     "numberofTwoOrMoreRaceStudents": 29,
                     "numberofUnspecifiedRaceStudents": null
                  },
                  {
                     "year": 2016,
                     "numberOfStudents": 395,
                     "percentFreeDiscLunch": 76.46,
                     "percentofAfricanAmericanStudents": 0.76,
                     "percentofAsianStudents": 2.03,
                     "percentofHispanicStudents": 42.53,
                     "percentofIndianStudents": 3.29,
                     "percentofPacificIslanderStudents": 0,
                     "percentofWhiteStudents": 47.34,
                     "percentofTwoOrMoreRaceStudents": 4.05,
                     "percentofUnspecifiedRaceStudents": null,
                     "teachersFulltime": 25,
                     "pupilTeacherRatio": 15.8,
                     "numberofAfricanAmericanStudents": 3,
                     "numberofAsianStudents": 8,
                     "numberofHispanicStudents": 168,
                     "numberofIndianStudents": 13,
                     "numberofPacificIslanderStudents": 0,
                     "numberofWhiteStudents": 187,
                     "numberofTwoOrMoreRaceStudents": 16,
                     "numberofUnspecifiedRaceStudents": null
                  }
               ],
               "isPrivate": false,
               "privateDays": null,
               "privateHours": null,
               "privateHasLibrary": null,
               "privateCoed": null,
               "privateOrientation": null,
               "hasBoundary": true
            },
            {
               "schoolid": "530825002361",
               "schoolName": "A-3 Multiagency Adolescent Prog",
               "phone": "(509) 354-6299",
               "url": "https://www.schooldigger.com/go/WA/schools/0825002361/school.aspx",
               "urlCompare": "https://www.schooldigger.com/go/WA/schools/0825002361/search.aspx",
               "address": {
                  "latLong": {
                     "latitude": 47.674349,
                     "longitude": -117.41781
                  },
                  "street": "1807 N. Washington",
                  "city": "Spokane",
                  "state": "WA",
                  "stateFull": "Washington",
                  "zip": "99205",
                  "zip4": "",
                  "cityURL": "https://www.schooldigger.com/go/WA/city/Spokane/search.aspx",
                  "zipURL": "https://www.schooldigger.com/go/WA/zip/99205/search.aspx",
                  "html": "1807 N. Washington<br />Spokane, WA 99205"
               },
               "lowGrade": "9",
               "highGrade": "12",
               "schoolLevel": "High",
               "isCharterSchool": "No",
               "isMagnetSchool": "(n/a)",
               "isVirtualSchool": "No",
               "isTitleISchool": "No",
               "isTitleISchoolwideSchool": "No",
               "district": {
                  "districtID": "5308250",
                  "districtName": "Spokane School District",
                  "url": "https://www.schooldigger.com/go/WA/district/08250/search.aspx",
                  "rankURL": "https://www.schooldigger.com/go/WA/districtrank.aspx?finddistrict=08250"
               },
               "county": {
                  "countyName": "Spokane",
                  "countyURL": "https://www.schooldigger.com/go/WA/county/Spokane/search.aspx"
               },
               "rankHistory": null,
               "rankMovement": null,
               "locationIsWithinBoundary": null,
               "schoolYearlyDetails": [
                  {
                     "year": 2017,
                     "numberOfStudents": 16,
                     "percentFreeDiscLunch": 62.5,
                     "percentofAfricanAmericanStudents": 6.25,
                     "percentofAsianStudents": null,
                     "percentofHispanicStudents": 6.25,
                     "percentofIndianStudents": null,
                     "percentofPacificIslanderStudents": null,
                     "percentofWhiteStudents": 75,
                     "percentofTwoOrMoreRaceStudents": 12.5,
                     "percentofUnspecifiedRaceStudents": null,
                     "teachersFulltime": 3.1,
                     "pupilTeacherRatio": 5.1,
                     "numberofAfricanAmericanStudents": 1,
                     "numberofAsianStudents": null,
                     "numberofHispanicStudents": 1,
                     "numberofIndianStudents": null,
                     "numberofPacificIslanderStudents": null,
                     "numberofWhiteStudents": 12,
                     "numberofTwoOrMoreRaceStudents": 2,
                     "numberofUnspecifiedRaceStudents": null
                  },
                  {
                     "year": 2016,
                     "numberOfStudents": 20,
                     "percentFreeDiscLunch": 80,
                     "percentofAfricanAmericanStudents": 0,
                     "percentofAsianStudents": 0,
                     "percentofHispanicStudents": 10,
                     "percentofIndianStudents": 0,
                     "percentofPacificIslanderStudents": 0,
                     "percentofWhiteStudents": 70,
                     "percentofTwoOrMoreRaceStudents": 20,
                     "percentofUnspecifiedRaceStudents": null,
                     "teachersFulltime": 3,
                     "pupilTeacherRatio": 6.6,
                     "numberofAfricanAmericanStudents": 0,
                     "numberofAsianStudents": 0,
                     "numberofHispanicStudents": 2,
                     "numberofIndianStudents": 0,
                     "numberofPacificIslanderStudents": 0,
                     "numberofWhiteStudents": 14,
                     "numberofTwoOrMoreRaceStudents": 4,
                     "numberofUnspecifiedRaceStudents": null
                  }
               ],
               "isPrivate": false,
               "privateDays": null,
               "privateHours": null,
               "privateHasLibrary": null,
               "privateCoed": null,
               "privateOrientation": null,
               "hasBoundary": true
            },
            {
               "schoolid": "530966001632",
               "schoolName": "Abraham Lincoln Elementary",
               "phone": "(509) 663-5710",
               "url": "https://www.schooldigger.com/go/WA/schools/0966001632/school.aspx",
               "urlCompare": "https://www.schooldigger.com/go/WA/schools/0966001632/search.aspx",
               "address": {
                  "latLong": {
                     "latitude": 47.40701,
                     "longitude": -120.3099
                  },
                  "street": "1224 Methow St.",
                  "city": "Wenatchee",
                  "state": "WA",
                  "stateFull": "Washington",
                  "zip": "98801",
                  "zip4": "",
                  "cityURL": "https://www.schooldigger.com/go/WA/city/Wenatchee/search.aspx",
                  "zipURL": "https://www.schooldigger.com/go/WA/zip/98801/search.aspx",
                  "html": "1224 Methow St.<br />Wenatchee, WA 98801"
               },
               "lowGrade": "K",
               "highGrade": "5",
               "schoolLevel": "Elementary",
               "isCharterSchool": "No",
               "isMagnetSchool": "(n/a)",
               "isVirtualSchool": "No",
               "isTitleISchool": "Yes",
               "isTitleISchoolwideSchool": "No",
               "district": {
                  "districtID": "5309660",
                  "districtName": "Wenatchee School District",
                  "url": "https://www.schooldigger.com/go/WA/district/09660/search.aspx",
                  "rankURL": "https://www.schooldigger.com/go/WA/districtrank.aspx?finddistrict=09660"
               },
               "county": {
                  "countyName": "Chelan",
                  "countyURL": "https://www.schooldigger.com/go/WA/county/Chelan/search.aspx"
               },
               "rankHistory": [
                  {
                     "year": 2018,
                     "rank": 981,
                     "rankOf": 1054,
                     "rankStars": 0,
                     "rankLevel": "Elementary",
                     "rankStatewidePercentage": 6.93,
                     "averageStandardScore": 10.7385
                  },
                  {
                     "year": 2017,
                     "rank": 998,
                     "rankOf": 1056,
                     "rankStars": 0,
                     "rankLevel": "Elementary",
                     "rankStatewidePercentage": 5.49,
                     "averageStandardScore": 9.13231
                  }
               ],
               "rankMovement": 17,
               "locationIsWithinBoundary": null,
               "schoolYearlyDetails": [
                  {
                     "year": 2017,
                     "numberOfStudents": 501,
                     "percentFreeDiscLunch": 78.64,
                     "percentofAfricanAmericanStudents": 0.4,
                     "percentofAsianStudents": null,
                     "percentofHispanicStudents": 76.25,
                     "percentofIndianStudents": 0.2,
                     "percentofPacificIslanderStudents": null,
                     "percentofWhiteStudents": 21.96,
                     "percentofTwoOrMoreRaceStudents": 1.2,
                     "percentofUnspecifiedRaceStudents": null,
                     "teachersFulltime": 36.4,
                     "pupilTeacherRatio": 13.7,
                     "numberofAfricanAmericanStudents": 2,
                     "numberofAsianStudents": null,
                     "numberofHispanicStudents": 382,
                     "numberofIndianStudents": 1,
                     "numberofPacificIslanderStudents": null,
                     "numberofWhiteStudents": 110,
                     "numberofTwoOrMoreRaceStudents": 6,
                     "numberofUnspecifiedRaceStudents": null
                  },
                  {
                     "year": 2016,
                     "numberOfStudents": 522,
                     "percentFreeDiscLunch": 83.14,
                     "percentofAfricanAmericanStudents": 0.57,
                     "percentofAsianStudents": 0,
                     "percentofHispanicStudents": 74.71,
                     "percentofIndianStudents": 0.38,
                     "percentofPacificIslanderStudents": 0,
                     "percentofWhiteStudents": 23.37,
                     "percentofTwoOrMoreRaceStudents": 0.96,
                     "percentofUnspecifiedRaceStudents": null,
                     "teachersFulltime": 34,
                     "pupilTeacherRatio": 15.3,
                     "numberofAfricanAmericanStudents": 3,
                     "numberofAsianStudents": 0,
                     "numberofHispanicStudents": 390,
                     "numberofIndianStudents": 2,
                     "numberofPacificIslanderStudents": 0,
                     "numberofWhiteStudents": 122,
                     "numberofTwoOrMoreRaceStudents": 5,
                     "numberofUnspecifiedRaceStudents": null
                  }
               ],
               "isPrivate": false,
               "privateDays": null,
               "privateHours": null,
               "privateHasLibrary": null,
               "privateCoed": null,
               "privateOrientation": null,
               "hasBoundary": true
            },
            {
               "schoolid": "539999944230",
               "schoolName": "Academy For Precision Learning",
               "phone": "(206) 427-0115",
               "url": "https://www.schooldigger.com/go/WA/schools/9999944230/school.aspx",
               "urlCompare": "https://www.schooldigger.com/go/WA/schools/9999944230/search.aspx",
               "address": {
                  "latLong": {
                     "latitude": null,
                     "longitude": null
                  },
                  "street": "PO Box 51241",
                  "city": "Seattle",
                  "state": "WA",
                  "stateFull": "Washington",
                  "zip": "98115",
                  "zip4": "",
                  "cityURL": "https://www.schooldigger.com/go/WA/city/Seattle/search.aspx",
                  "zipURL": "https://www.schooldigger.com/go/WA/zip/98115/search.aspx",
                  "html": "PO Box 51241<br />Seattle, WA 98115"
               },
               "lowGrade": "K",
               "highGrade": "12",
               "schoolLevel": "Private",
               "isCharterSchool": "(n/a)",
               "isMagnetSchool": "(n/a)",
               "isVirtualSchool": "(n/a)",
               "isTitleISchool": "(n/a)",
               "isTitleISchoolwideSchool": "(n/a)",
               "county": {
                  "countyName": "King",
                  "countyURL": "https://www.schooldigger.com/go/WA/county/King/search.aspx"
               },
               "rankHistory": null,
               "rankMovement": null,
               "locationIsWithinBoundary": null,
               "schoolYearlyDetails": [
                  {
                     "year": 2016,
                     "numberOfStudents": 102,
                     "percentFreeDiscLunch": null,
                     "percentofAfricanAmericanStudents": 1.96,
                     "percentofAsianStudents": 25.49,
                     "percentofHispanicStudents": 1.96,
                     "percentofIndianStudents": 0,
                     "percentofPacificIslanderStudents": 0,
                     "percentofWhiteStudents": 70.59,
                     "percentofTwoOrMoreRaceStudents": 0,
                     "percentofUnspecifiedRaceStudents": null,
                     "teachersFulltime": 11,
                     "pupilTeacherRatio": 9.2,
                     "numberofAfricanAmericanStudents": 2,
                     "numberofAsianStudents": 26,
                     "numberofHispanicStudents": 2,
                     "numberofIndianStudents": 0,
                     "numberofPacificIslanderStudents": 0,
                     "numberofWhiteStudents": 72,
                     "numberofTwoOrMoreRaceStudents": 0,
                     "numberofUnspecifiedRaceStudents": null
                  },
                  {
                     "year": 2014,
                     "numberOfStudents": 90,
                     "percentFreeDiscLunch": null,
                     "percentofAfricanAmericanStudents": 3.33,
                     "percentofAsianStudents": 25.56,
                     "percentofHispanicStudents": 5.56,
                     "percentofIndianStudents": 1.11,
                     "percentofPacificIslanderStudents": 1.11,
                     "percentofWhiteStudents": 60,
                     "percentofTwoOrMoreRaceStudents": 3.33,
                     "percentofUnspecifiedRaceStudents": null,
                     "teachersFulltime": 8.8,
                     "pupilTeacherRatio": 10.2,
                     "numberofAfricanAmericanStudents": 3,
                     "numberofAsianStudents": 23,
                     "numberofHispanicStudents": 5,
                     "numberofIndianStudents": 1,
                     "numberofPacificIslanderStudents": 1,
                     "numberofWhiteStudents": 54,
                     "numberofTwoOrMoreRaceStudents": 3,
                     "numberofUnspecifiedRaceStudents": null
                  }
               ],
               "isPrivate": true,
               "privateDays": 190,
               "privateHours": 6.5,
               "privateHasLibrary": false,
               "privateCoed": "Coed",
               "privateOrientation": "Nonsectarian",
               "hasBoundary": false
            },
            {
               "schoolid": "539999944231",
               "schoolName": "Academy NW/Family Academy",
               "phone": "(206) 246-9227",
               "url": "https://www.schooldigger.com/go/WA/schools/9999944231/school.aspx",
               "urlCompare": "https://www.schooldigger.com/go/WA/schools/9999944231/search.aspx",
               "address": {
                  "latLong": {
                     "latitude": null,
                     "longitude": null
                  },
                  "street": "PO Box 66839",
                  "city": "Seattle",
                  "state": "WA",
                  "stateFull": "Washington",
                  "zip": "98166",
                  "zip4": "",
                  "cityURL": "https://www.schooldigger.com/go/WA/city/Seattle/search.aspx",
                  "zipURL": "https://www.schooldigger.com/go/WA/zip/98166/search.aspx",
                  "html": "PO Box 66839<br />Seattle, WA 98166"
               },
               "lowGrade": "1",
               "highGrade": "12",
               "schoolLevel": "Private",
               "isCharterSchool": "(n/a)",
               "isMagnetSchool": "(n/a)",
               "isVirtualSchool": "(n/a)",
               "isTitleISchool": "(n/a)",
               "isTitleISchoolwideSchool": "(n/a)",
               "county": {
                  "countyName": "King",
                  "countyURL": "https://www.schooldigger.com/go/WA/county/King/search.aspx"
               },
               "rankHistory": null,
               "rankMovement": null,
               "locationIsWithinBoundary": null,
               "schoolYearlyDetails": [
                  {
                     "year": 2016,
                     "numberOfStudents": 311,
                     "percentFreeDiscLunch": null,
                     "percentofAfricanAmericanStudents": 1.93,
                     "percentofAsianStudents": 2.57,
                     "percentofHispanicStudents": 3.54,
                     "percentofIndianStudents": 1.61,
                     "percentofPacificIslanderStudents": 0,
                     "percentofWhiteStudents": 68.17,
                     "percentofTwoOrMoreRaceStudents": 22.19,
                     "percentofUnspecifiedRaceStudents": null,
                     "teachersFulltime": 17.9,
                     "pupilTeacherRatio": 17.3,
                     "numberofAfricanAmericanStudents": 6,
                     "numberofAsianStudents": 8,
                     "numberofHispanicStudents": 11,
                     "numberofIndianStudents": 5,
                     "numberofPacificIslanderStudents": 0,
                     "numberofWhiteStudents": 212,
                     "numberofTwoOrMoreRaceStudents": 69,
                     "numberofUnspecifiedRaceStudents": null
                  },
                  {
                     "year": 2014,
                     "numberOfStudents": 290,
                     "percentFreeDiscLunch": null,
                     "percentofAfricanAmericanStudents": 2.07,
                     "percentofAsianStudents": 3.79,
                     "percentofHispanicStudents": 3.45,
                     "percentofIndianStudents": 0.69,
                     "percentofPacificIslanderStudents": 0,
                     "percentofWhiteStudents": 90,
                     "percentofTwoOrMoreRaceStudents": 0,
                     "percentofUnspecifiedRaceStudents": null,
                     "teachersFulltime": 20.4,
                     "pupilTeacherRatio": 14.2,
                     "numberofAfricanAmericanStudents": 6,
                     "numberofAsianStudents": 11,
                     "numberofHispanicStudents": 10,
                     "numberofIndianStudents": 2,
                     "numberofPacificIslanderStudents": 0,
                     "numberofWhiteStudents": 261,
                     "numberofTwoOrMoreRaceStudents": 0,
                     "numberofUnspecifiedRaceStudents": null
                  }
               ],
               "isPrivate": true,
               "privateDays": 180,
               "privateHours": 5.5,
               "privateHasLibrary": false,
               "privateCoed": "Coed",
               "privateOrientation": "Christian (no specific denomination)",
               "hasBoundary": false
            },
            {
               "schoolid": "539999924062",
               "schoolName": "Academy Schools",
               "phone": "(206) 588-0860",
               "url": "https://www.schooldigger.com/go/WA/schools/9999924062/school.aspx",
               "urlCompare": "https://www.schooldigger.com/go/WA/schools/9999924062/search.aspx",
               "address": {
                  "latLong": {
                     "latitude": 47.472444,
                     "longitude": -122.255825
                  },
                  "street": "14601 Interurban Ave S",
                  "city": "Tukwila",
                  "state": "WA",
                  "stateFull": "Washington",
                  "zip": "98168",
                  "zip4": "",
                  "cityURL": "https://www.schooldigger.com/go/WA/city/Tukwila/search.aspx",
                  "zipURL": "https://www.schooldigger.com/go/WA/zip/98168/search.aspx",
                  "html": "14601 Interurban Ave S<br />Tukwila, WA 98168"
               },
               "lowGrade": "PK",
               "highGrade": "12",
               "schoolLevel": "Private",
               "isCharterSchool": "(n/a)",
               "isMagnetSchool": "(n/a)",
               "isVirtualSchool": "(n/a)",
               "isTitleISchool": "(n/a)",
               "isTitleISchoolwideSchool": "(n/a)",
               "county": {
                  "countyName": "King",
                  "countyURL": "https://www.schooldigger.com/go/WA/county/King/search.aspx"
               },
               "rankHistory": null,
               "rankMovement": null,
               "locationIsWithinBoundary": null,
               "schoolYearlyDetails": [
                  {
                     "year": 2016,
                     "numberOfStudents": 53,
                     "percentFreeDiscLunch": null,
                     "percentofAfricanAmericanStudents": 9.43,
                     "percentofAsianStudents": 30.19,
                     "percentofHispanicStudents": 3.77,
                     "percentofIndianStudents": 3.77,
                     "percentofPacificIslanderStudents": 3.77,
                     "percentofWhiteStudents": 37.74,
                     "percentofTwoOrMoreRaceStudents": 0,
                     "percentofUnspecifiedRaceStudents": null,
                     "teachersFulltime": 9,
                     "pupilTeacherRatio": 5.2,
                     "numberofAfricanAmericanStudents": 5,
                     "numberofAsianStudents": 16,
                     "numberofHispanicStudents": 2,
                     "numberofIndianStudents": 2,
                     "numberofPacificIslanderStudents": 2,
                     "numberofWhiteStudents": 20,
                     "numberofTwoOrMoreRaceStudents": 0,
                     "numberofUnspecifiedRaceStudents": null
                  },
                  {
                     "year": 2014,
                     "numberOfStudents": 43,
                     "percentFreeDiscLunch": null,
                     "percentofAfricanAmericanStudents": 6.98,
                     "percentofAsianStudents": 16.28,
                     "percentofHispanicStudents": 0,
                     "percentofIndianStudents": 2.33,
                     "percentofPacificIslanderStudents": 13.95,
                     "percentofWhiteStudents": 37.21,
                     "percentofTwoOrMoreRaceStudents": 2.33,
                     "percentofUnspecifiedRaceStudents": null,
                     "teachersFulltime": 7.3,
                     "pupilTeacherRatio": 4.6,
                     "numberofAfricanAmericanStudents": 3,
                     "numberofAsianStudents": 7,
                     "numberofHispanicStudents": 0,
                     "numberofIndianStudents": 1,
                     "numberofPacificIslanderStudents": 6,
                     "numberofWhiteStudents": 16,
                     "numberofTwoOrMoreRaceStudents": 1,
                     "numberofUnspecifiedRaceStudents": null
                  }
               ],
               "isPrivate": true,
               "privateDays": 168,
               "privateHours": 7,
               "privateHasLibrary": true,
               "privateCoed": "Coed",
               "privateOrientation": "Nonsectarian",
               "hasBoundary": false
            },
            {
               "schoolid": "530048003466",
               "schoolName": "Acceleration Academy",
               "phone": "(253) 267-1045",
               "url": "https://www.schooldigger.com/go/WA/schools/0048003466/school.aspx",
               "urlCompare": "https://www.schooldigger.com/go/WA/schools/0048003466/search.aspx",
               "address": {
                  "latLong": {
                     "latitude": 47.109051,
                     "longitude": -122.435396
                  },
                  "street": "16218 Pacific Ave",
                  "city": "Spanaway",
                  "state": "WA",
                  "stateFull": "Washington",
                  "zip": "98387",
                  "zip4": "",
                  "cityURL": "https://www.schooldigger.com/go/WA/city/Spanaway/search.aspx",
                  "zipURL": "https://www.schooldigger.com/go/WA/zip/98387/search.aspx",
                  "html": "16218 Pacific Ave<br />Spanaway, WA 98387"
               },
               "lowGrade": "9",
               "highGrade": "12",
               "schoolLevel": "High",
               "isCharterSchool": "No",
               "isMagnetSchool": "(n/a)",
               "isVirtualSchool": "No",
               "isTitleISchool": "No",
               "isTitleISchoolwideSchool": "No",
               "district": {
                  "districtID": "5300480",
                  "districtName": "Bethel School District",
                  "url": "https://www.schooldigger.com/go/WA/district/00480/search.aspx",
                  "rankURL": "https://www.schooldigger.com/go/WA/districtrank.aspx?finddistrict=00480"
               },
               "county": {
                  "countyName": "Pierce",
                  "countyURL": "https://www.schooldigger.com/go/WA/county/Pierce/search.aspx"
               },
               "rankHistory": null,
               "rankMovement": null,
               "locationIsWithinBoundary": null,
               "schoolYearlyDetails": [
                  {
                     "year": 2017,
                     "numberOfStudents": 227,
                     "percentFreeDiscLunch": 55.51,
                     "percentofAfricanAmericanStudents": 14.1,
                     "percentofAsianStudents": 3.52,
                     "percentofHispanicStudents": 13.22,
                     "percentofIndianStudents": 2.2,
                     "percentofPacificIslanderStudents": 3.52,
                     "percentofWhiteStudents": 53.3,
                     "percentofTwoOrMoreRaceStudents": 10.13,
                     "percentofUnspecifiedRaceStudents": null,
                     "teachersFulltime": null,
                     "pupilTeacherRatio": null,
                     "numberofAfricanAmericanStudents": 32,
                     "numberofAsianStudents": 8,
                     "numberofHispanicStudents": 30,
                     "numberofIndianStudents": 5,
                     "numberofPacificIslanderStudents": 8,
                     "numberofWhiteStudents": 121,
                     "numberofTwoOrMoreRaceStudents": 23,
                     "numberofUnspecifiedRaceStudents": null
                  },
                  {
                     "year": 2016,
                     "numberOfStudents": 139,
                     "percentFreeDiscLunch": 43.17,
                     "percentofAfricanAmericanStudents": 17.27,
                     "percentofAsianStudents": 2.16,
                     "percentofHispanicStudents": 14.39,
                     "percentofIndianStudents": 2.16,
                     "percentofPacificIslanderStudents": 1.44,
                     "percentofWhiteStudents": 56.12,
                     "percentofTwoOrMoreRaceStudents": 6.47,
                     "percentofUnspecifiedRaceStudents": null,
                     "teachersFulltime": null,
                     "pupilTeacherRatio": null,
                     "numberofAfricanAmericanStudents": 24,
                     "numberofAsianStudents": 3,
                     "numberofHispanicStudents": 20,
                     "numberofIndianStudents": 3,
                     "numberofPacificIslanderStudents": 2,
                     "numberofWhiteStudents": 78,
                     "numberofTwoOrMoreRaceStudents": 9,
                     "numberofUnspecifiedRaceStudents": null
                  }
               ],
               "isPrivate": false,
               "privateDays": null,
               "privateHours": null,
               "privateHasLibrary": null,
               "privateCoed": null,
               "privateOrientation": null,
               "hasBoundary": false
            }
         ]
      }
   
